### DISCUSSION TITLE
HY02B05-WIFI Thermostat

### DISCUSSION THREAD

**Discussion by yvesdm3000** [arendst/Tasmota#10513] [Show and tell]
I managed to support this thermostat using Tasmota's rule system in hassio:

![DSC_0832](https://user-images.githubusercontent.com/1717312/104136554-49e76280-5397-11eb-8a89-ac18c0b45439.JPG)

![DSC_0831](https://user-images.githubusercontent.com/1717312/104136565-5cfa3280-5397-11eb-899d-080b9ea5717b.JPG)

It looks a lot like the Beca thermostat, it uses the TuyaMCU, but with some specialities.

```
DpId 1: Boolean, Switches the device on or off, display clears, I hear the relay clicking when it's heating, same as power button
DpId 2: Integer, target temperature x 10 so 240 is 24.0 degrees C
DpId 3: Current measured temperature x 10, so 215 is 21.5 degrees C
DpId 4: Enum,
0 = Manual,
1 = Auto,
2 = Bag icon: Holiday mode,
3 = Manual override I think, when updating DpId2, this switches to 3
4 = Disabled I think (no state icon displayed)
5 = Disabled I think (no state icon displayed)
DpId 6: Boolean, Display lock
DpId 101: Boolean, function unknown, (toggling doesn't update the value)
DpId 102: Boolean, Heating relay state, (toggling doesn't update the value)
DpId 103: Integer, function unknown
DpId 104: Integer, function unknown
DpId 105: Integer, function unknown
DpId 106: Boolean, function unknown
DpId 107: Boolean, function unknown
DpId 108: Boolean, function unknown, (toggling doesn't update the value)
DpId 109: Integer, function unknown
DpId 110: Integer, function unknown
DpId 111: Integer, function unknown
DpId 112: Integer, function unknown
DpId 113: Integer, function unknown
DpId 114: Integer, function unknown
DpId 115: Integer, function unknown
DpId 116: Enum, function unknown
DpId 117: Enum, function unknown
DpId 118: Enum, function unknown
```

This is the script I used to make it link to MQTT:

```
Rule1 
  on mqtt#connected DO subscribe tempset, cmnd/%topic%/TEMPSET endon 
  on TuyaSNS#Temperature do var1=%value%/10.0 endon 
  on var1#state do publish tele/Thermostat/TEMPERATURE %var1% endon 
  on TuyaSNS#TempSet do var2=%value%/10.0 endon 
  on var2#state do publish tele/Thermostat/TEMPSET %var2% endon 
  on event#TEMPSET do var3=%value%*10 endon 
  on var3#state do TuyaSend2 2,%value% endon
```

In Home-Assistant:
```yaml
climate:
  - platform: mqtt
    name: Tasmota Thermostat
    modes:
      - "off"
      - "heat"
      - "auto"
    power_command_topic: cmnd/Thermostat/POWER
    mode_command_topic: cmnd/Thermostat/cmnd/MODE
    temperature_state_topic: tele/Thermostat/TEMPSET
    temperature_command_topic: cmnd/Thermostat/TEMPSET
    current_temperature_topic: tele/Thermostat/TEMPERATURE
    precision: 0.5
    temp_step: 0.5
    unique_id: thermostat1
```

I can probably build something to link DpId4 to hassio, but I didn't bother yet for now.

To link tuya to Tasmota, I used these commands in Console:
```
TuyaMCU 11,1
TuyaMCU 72,2
TuyaMCU 71,3
TuyaMCU 26,4
```
My latest build at https://github.com/yvesdm3000/TasmotaFirmwares/tree/main/HY02B05-WIFI/9.2  doesn't need the above Rules to divide the temperatures, that is now fixed upstream and in my build.

**Comment by SergyiSviderskii** [comment]
DpId 102: Boolean-relay output (load)
DpId 103: Integer- external sensor temperature
DpId 104: Integer-number of vacation days
DpId 105: Integer-vacation temperature
DpId 106: Boolean-high temperature protection was cancelled ( A6 - [--] - customization HY02B05)
DpId 107: Boolean-low temperature protection was cancelled ( A7 - [--] - customization HY02B05)
DpId 109: Integer- measure temperature calibrtion -9/+9 ( A1 - customization HY02B05)
DpId 110: Integer- temperature control return difference setting 0.5/2.5 ( A2 - customization HY02B05)
DpId 111: Integer -external sensors limit temperature control return difference 1/9 ( A2 - customization HY02B05)
DpId 112: Integer-limit value of high temperature for external sensor ( A6 - 35°C/70°C  - customization HY02B05)
DpId 113: Integer-limit value of low temperature for external sensor ( A7 - 1°C/10°C  - customization HY02B05)
DpId 114: Integer-setting temperature highest limit 20°C/70°C ( A9 - customization HY02B05 - max temp. )
DpId 115: Integer-setting temperature lowest limit 1°C/10°C ( A8 - customization HY02B05 - min temp. )
DpId 116: Enum-options of sensor control N1,N2,N3 ( A4 - customization HY02B05  )
DpId 117: Enum-power with memory function 0-memory,1-off,2-on ( AB- customization HY02B05  )
DpId 118: Enum-weekly programming selection 0-5+2, 1-6+1, 2-7 ( AC- customization HY02B05  )
and
DpId 119,DpId 120,:string- 6 -boundary points working days or week 7 days
DpId 121,DpId 122:string- 6 -boundary points weekend
(hours, minutes, temperature)
call:
1 on / off on the device 
2 write or read min temp. or max temp.

the question is how do you synchronize time
thanks.

**Reply by yvesdm3000** [reply]
Hello

I had a pull request to fix the time issue and was merged a while ago:

https://github.com/arendst/Tasmota/pull/10428

It should be in the next release.

Many thanks for the clarification on the dpid table!

Yves

**Comment by SergyiSviderskii** [comment]
I found the following.
1 firmware with a script (compile your own assembly)
2 the code may be crooked, but the meaning is clear:

>D
sum=0
var1=0
var2=1
var3=0
var4=0
t:timer1=0

>F
if wifis==1
then
     if year==0
        or
        year==1970
     then
     else
          if time==0
          then 
             var2=1
          endif
          if var2==1
          then
               if secs==0
               then     
                   var1=wday-1
                   if var1==0 
                   then
                       var1=7
                   endif
                   var3=year-2000
                   sum=36+var3+month+day+hours+mins+secs+var1
                   =>SerialSend5 55AA001C000801%hn(var3)%%hn(month)%%hn(day)%%hn(hours)%%hn(mins)%%hn(secs)%%hn(var1)%%hn(sum)%
                   var2=0
                   var3=1
                   timer1=2
               endif
          endif
     endif   
endif

if var3==1
then
     if timer1==0
     then
          =>SerialSend5 55aa000300010407
          var3=0
          var4=1
          timer1=1
     endif
endif

if var4==1
then
     if timer1==0
     then
          =>SerialSend5 55aa000300010306
          var4=0
     endif
endif
1:                    =>SerialSend5 55AA001C000801%hn(var3)%%hn(month)%%hn(day)%%hn(hours)%%hn(mins)%%hn(secs)%%hn(var1)%%hn(sum)%
recording in the clock of the thermostat:
2:=>SerialSend5 55aa000300010407
3: =>SerialSend5 55aa000300010306
give a delay between commands 1 sec.
somewhere like that.
now I have no time to finish this.

**Reply by yvesdm3000** [reply]
The time is already fixed in tasmota master.  Confirmed to be working.

**Reply by yvesdm3000** [reply]
Oh and I forgot: the time update needs to be enabled in a custom build of Tasmota, by default tuya-time update is disabled, probably because not all tuya-mcu devices have this.

**Reply by SergyiSviderskii** [reply]
ok

**Reply by yvesdm3000** [reply]
Do you want my build? I could publish the config & binary.

But I'm currently experimenting with https://github.com/klausahrenberg/WThermostatBeca, it seems to have more bits implemented for a thermostat, although I think these feature could easily be added to Tasmota too.

Yves

**Comment by yvesdm3000** [comment]
I published my binary here:

https://github.com/yvesdm3000/TasmotaFirmwares

**Comment by SergyiSviderskii** [comment]
Hello!
Do you have original firmware for this thermostat?
Thanks.

**Reply by sfromis** [reply]
Normally, it would not work getting factory firmware from another device, as Tuya firmware is usually locked to the MAC address of the ESP8266 chip.

**Comment by SergyiSviderskii** [comment]
ok
Thanks.

**Comment by bluespirit08** [comment]
Hi! I am a newbie on TASMOTA and HASSIO, started just some weeks ago. Have a longer track record in professional programming but a lot of years ago, and just some recent arduino projects. Started HomeAssistant XMas incl. some SONOFF deploying TASMOTA.
I have the same thermostat in my bathroom and also want to integrate this.
Can I just use your binary , flash it and than configure what template?
Can you please share the template you are using?  Do you use SetOption19 true for autodiscovery via MQTT?
Hope my questions are not too stupid ;| Thanks for your support!

**Reply by yvesdm3000** [reply]
Hi bluespirit08,

The script above works with the template base for 'TuyaMCU' with everything set to 'User'.

I'm currently working on the code to get better and easier support for this thermostat in my branch at https://github.com/yvesdm3000/Tasmota on the branch tuya_thermostat. This work should replace the scripts above. I am step by step submitting small patches to the main repo fixing small bugs and I intend to document the new and better way of integrating the thermostat in tasmota.

I did not test setoption19 yet, but once I get to that point of supporting auto-discovery, I would use the tasmota based auto-detection (setoption19 0) since that will be the best option in the longer run.

This is how it currently looks for now:
![image](https://user-images.githubusercontent.com/1717312/107526324-065f5e80-6bb8-11eb-88f7-c93f854ecdc6.png)

Yves

**Reply by bluespirit08** [reply]
Thanks Yves! Very much appreciated.
I will check out today. Will put your binary first on a standalone DS01 module for test and then unsolder the ESPmodule in the thermostat for flashing ...
Understood that this is actually the configuration for the ESP tamota software on the com protocol for the tuya MCU (I guess it is a PIC). 
I will report back but seems straigth forward ;)

**Reply by bluespirit08** [reply]
By the way is there a newer version of the binary compared to here ?
https://github.com/yvesdm3000/TasmotaFirmwares/tree/main/HY02B05-WIFI/9.2
Thanks again! Marcus

**Reply by yvesdm3000** [reply]
I uploaded a new firmware under 9.2.0.7. Some fixes have been submitted and accepted upstream. 

This build has a lot of functionality disabled since this thermostat doesn't support many of these features.

Don't forget to do 

TuyaMCU 11,1
TuyaMCU 72,2
TuyaMCU 71,3
TuyaMCU 26,4

This is to map the tuya addresses to tasmota functions.

Yves

**Comment by jaymemaurice** [comment]
I'm glad I didn't discover your write up earlier... I wouldn't have changed the TuyaMCU driver.
Awesome work explaining the rules which can be interpolated for doing non-standard division.

**Reply by bluespirit08** [reply]
Hi Maurice, did not really get your point ;|

**Reply by jaymemaurice** [reply]
Sorry this was meant for @yvesdm3000 on the main thread. I had an inkbird thermostat which was Tuya based. I did the patch that allowed tempres to turn the integer from TuyaMCU into a signed float. If I discovered this really clever way of using rules I would not have gotten involved in contributing. Let me read on your issue and I will see if I have ideas.

**Comment by bluespirit08** [comment]
Actually had now chance to proceed with the Thermostat yet - tzo busy with other things. Seems to a quite old version ... and I was not able to find any documentation on the ESP module and what is the pinning and how to flash ... will check it out with another ESP module ;)

**Comment by bluespirit08** [comment]
![IMG-2399](https://user-images.githubusercontent.com/78846075/110201354-ed6a6600-7e62-11eb-98de-a8113896ecfd.jpg)
![IMG-2393](https://user-images.githubusercontent.com/78846075/110201355-ee02fc80-7e62-11eb-8dd9-dc11fa137f9d.jpg)
![IMG-2395](https://user-images.githubusercontent.com/78846075/110201357-ef342980-7e62-11eb-83cf-9155e8e2dc13.jpg)
![IMG-2398](https://user-images.githubusercontent.com/78846075/110201359-f0fded00-7e62-11eb-80a9-a688556f3c18.jpg)
Any hints?

**Reply by jaymemaurice** [reply]
This one doesn’t look tuyamcu based to me... I could be wrong. Most tuyamcu products I’ve seen have used holtek. I’m not familiar with that esp chip either but how I find the serial lines is using a multimeter to check for continuity between one a pin on the esp and any of the pins on the mcu. Do continuity checks for ground and power.

**Reply by jaymemaurice** [reply]
It might be similar to this one. Tywe3s. But double check first with continuity checks.  It could also be Realtek based...


![40108360-7344-4EAD-B179-6A6BC932F7BE](https://user-images.githubusercontent.com/38895319/110212277-a1222480-7e68-11eb-8bc7-c662ae2fbc5b.jpeg)

**Reply by yvesdm3000** [reply]
Mac address doens't indicate an esp chip. I would replace the board with a esp12f one.

**Comment by KG3RK3N** [comment]
Hello, I have just flashed your firmware on my thermostat and it works great. My home assistant server has discovered it perfectly.
Do you have any plans to support the external temperature sensor and the current state for the relay?
Or do you think thats the WThermostatBeca firmware is a better choice? Whats your experience there?

**Reply by barbudor** [reply]
External temperature sensor is supported by Tasmota.
You can receive temperature from MQTT
Or even subscribe to a mqtt topic from another sensor.
What are you exactly looking for?

https://tasmota.github.io/docs/Thermostat

**Reply by yvesdm3000** [reply]
@barbudor The TY02B05-WIFI thermostat has a connector to connect an external temperature sensor. I don't use it nor do I have a need for it. I made this patch to better support the thermostat using Tasmota because I also wanted some rules to trigger other things when heating is requested/not requested without an external system like Home-Assistant. WThermostatBeca is very limited in that aspect. 
I do think there is a Tuya dpId that returns the value from the external temperature sensor. What do you intend to do with the value ?

**Comment by Toolmaster30** [comment]
Hallo, es würde mich sehr freuen wenn du deine Tasmota Version auf den aktuellen Stand bringen könntest. Mein th213 Thermostat arbeitet fast perfekt mit deiner Version. Leider lässt sich diese Tasmota Version nicht in Alexa einbinden.

Grüße Manuela

**Comment by Toolmaster30** [comment]
Hello, I would be very happy if you could update your Tasmota version. My th213 thermostat works almost perfectly with your version. Unfortunately, this Tasmota version cannot be integrated into Alexa.

Greetings Manuela

**Comment by Toolmaster30** [comment]
And I have one more question, how to change the mode via Mqtt?
Greetings Manuela

**Reply by sfromis** [reply]
Any console command is also available via MQTT.
https://tasmota.github.io/docs/MQTT/#commands-over-mqtt

**Comment by nightmare-rg** [comment]
@yvesdm3000 Are you planning to merge your changes with an actual tasmota version? I tried 12.5. version and my WHT-HY609 doesn't work correctly. With your firmware and some small adjusts for Homeassistant it works perfectly.

here are my changes for homeassistant to work with the latest version:

```
mqtt:
  climate:
    - name: Wohnzimmer Fußbodenheizung
      modes:
        - "off"
        - "heat"
      power_command_topic: cmnd/wohnzimmer_hk/POWER
      mode_command_topic: cmnd/wohnzimmer_hk/cmnd/MODE
      mode_state_topic: stat/wohnzimmer_hk/POWER
      mode_state_template: >
        {% if value == 'ON' %}
          heat
        {% else %}
          off
        {% endif %}
      temperature_state_topic: tele/wohnzimmer_hk/SENSOR
      temperature_state_template: "{{ value_json.TuyaSNS.TempSet }}"
      temperature_command_topic: cmnd/wohnzimmer_hk/Tuyasend2
      temperature_command_template: "2,{{ value | float * 10 }}"
      current_temperature_topic: tele/wohnzimmer_hk/SENSOR
      current_temperature_template: "{{ value_json.TuyaSNS.Temperature }}"
      precision: 0.5
      temp_step: 0.5
      unique_id: Wohnzimmer_HK 
    - name: Büro Fußbodenheizung
      modes:
        - "off"
        - "heat"
      power_command_topic: cmnd/buero_hk/POWER
      mode_command_topic: cmnd/buero_hk/cmnd/MODE
      mode_state_topic: stat/buero_hk/POWER
      mode_state_template: >
        {% if value == 'ON' %}
          heat
        {% else %}
          off
        {% endif %}
      temperature_state_topic: tele/buero_hk/SENSOR
      temperature_state_template: "{{ value_json.TuyaSNS.TempSet }}"
      temperature_command_topic: cmnd/buero_hk/Tuyasend2
      temperature_command_template: "2,{{ value | float * 10 }}"
      current_temperature_topic: tele/buero_hk/SENSOR
      current_temperature_template: "{{ value_json.TuyaSNS.Temperature }}"
      precision: 0.5
      temp_step: 0.5
      unique_id: Buero_HK 
  sensor:
```
