### DISCUSSION TITLE
Shutters Mode - Listen for position on single MQTT topic [solved]

### DISCUSSION THREAD

**Discussion by ma-zal** [arendst/Tasmota#11681] [Q&A] [answered]
Issue overview
--------------

When Tasmota is in shutters mode (`SetOption80 1`), it is not possible to listen for current shutters position on single MQTT topic.

Behavior details
----------------

When shutters are in movement, then position is periodically reported by:

```
MQTT: stat/%topic%/RESULT = {"Shutter1":{"Position":3,"Direction":1,"Target":100}}
MQTT: stat/%topic%/RESULT = {"Shutter1":{"Position":5,"Direction":1,"Target":100}}
MQTT: stat/%topic%/RESULT = {"Shutter1":{"Position":8,"Direction":1,"Target":100}}
```

When movement get to be completed/stopped, then position reported by:

```
MQTT: stat/%topic%/SHUTTER1 = 17
MQTT: stat/%topic%/RESULT = {"Shutter1":{"Position":17,"Direction":0,"Target":17}}
```

But each `TelePeriod` the position is reported in different MQTT topic:

```
MQTT: tele/%topic%/SENSOR = {"Time":"2021-04-12T00:11:37","Shutter1":{"Position":0,"Direction":0,"Target":0}}
```

Suggested improvement
------------------

As possible improvement (issue solution) I see to add some `SetOption` with function:

"Send tele/%topic%/SENSOR in addition to stat/%topic%/RESULT for commands: `ShutterClose`, `ShutterOpen`, `ShutterStop`, `ShutterToggle`, `ShutterPosition` and any command causing a shutter position to be changed."

_Note: Similar behavior is already available for switches by option `SetOption59 1` (but there is no effect in case of Shutters mode):_

_`SetOption59 1` documentation: "Send tele/%topic%/STATE in addition to stat/%topic%/RESULT for commands: `State`, `Power` and any command causing a light to be turned on."_

Why it is issue
---------------

When shutters are integrated to Home Assistant (HASS), then a position can be listened from `SENSOR` (first example), from `RESULT` (2nd example), or from `SHUTTER1` (3rd example).

There are issues in each integration:

- 1st integration (`SENSOR`) issue: Position is not updated in HASS immediately durning and after shutters movements.

- 2nd integration (`RESULT`) issue: Position is not updated in HASS by `TelePeriod`.

- 3rd integration (`SHUTTER1`) issue: Position is not updated in HASS by `TelePeriod` and not updated continuously during shutters movements.

1st HA integration example:

```yaml
cover:
  - platform: mqtt
    name: "My Blinds"
    position_topic: "tele/%topic%/SENSOR"
    position_template: "{{ json_value.Shutter1.Position }}"
    #... And other parameters
```

2nd HA integration example

```yaml
cover:
  - platform: mqtt
    name: "My Blinds"
    position_topic: "stat/%topic%/RESULT"
    position_template: "{{ json_value.Shutter1.Position }}"   # Note: Simplified! Missing detection, if `Position` really sent in JSON, because in some results, this value is not present.
    #... And other parameters
```

3rd HA integration example:

```yaml
cover:
  - platform: mqtt
    name: "My Blinds"
    position_topic: "stat/%topic%/SHUTTER1"
    #... And other parameters
```

**Comment by arendst** [comment]
Play with ``SO4 1``

**Reply by ma-zal** [reply]
Hi @arendst . Thanks for quick response. :)

`SetOption4 1` changes result topic from `stat/%topic%/RESULT` to `stat/%topic%/SHUTTER`.
However `TelePeriod` is still reporting into `stat/%topic%/SENSOR` independently on `SetOption4 1`.

Therefore no change in issue: The `TelePeriod` still uses different topic (`SENSOR`) in comparation with shutter movements (`RESULT` or `SHUTTER`)

**Reply by barbudor** [reply]
What is the purpose of getting a Shutter position as a Sensor ?
If you can't get HA to listen to 2 different topics (I would have no problems in NodeRed), just create a rule to republish the Shutter on every tele-SENSOR on the topic of your liking.

**Reply by ma-zal** [reply]
> What is the purpose of getting a Shutter position as a Sensor ?

Answer: `SENSOR` means MQTT topic `stat/%topic%/SENSOR`. The idea is: In case Home Assistant is restarted, or some wifi outage, then HASS get lost information about shutter position. Therefore the idea is to align current blinds position with HASS by `SENSOR` MQTT message. This `SENSOR` message is sent periodicaly (based on `TelePeriod`). So when HASS get lost position value, then app will receive it again on next `TelePeriod`.

> If you can't get HA to listen to 2 different topics (I would have no problems in NodeRed), just create a rule to republish the Shutter on every tele-SENSOR on the topic of your liking.

Answer. Great idea. I immediatelly tried automation:

```yaml
alias: "Blinds - rewrite position from MQTT SENSOR to SHUTTER"
trigger:
  - platform: mqtt
    topic: tele/tasmota_tx1/SENSOR
action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/SHUTTER
      payload: "{{ trigger.payload }}"
```

But Tasmota is not happy if somebody writes into own MQTT topic. If somebody writes into `cmnd/tasmotas/SHUTTER`, it will cause exception and device restart. :(

```
QT: tele/tasmota_tx1/INFO3 = {"RestartReason":{"Exception":0,"Reason":"Exception", ...}}
QPC: Reset
```

**Reply by barbudor** [reply]
If somebody writes to "cmnd/tasmotas/SHUTTER" it send the SHUTTER command to all tasmotas
If it restart the devices, it's a bug a it shouldn't

I was meaning a Rule on the tasmota device such as 
```
on tele-Shutter1#Position do var1 %value% endon
on tele-Shutter1#Direction do var2 %value% endon
on tele-Shutter1#Target do publish stat/%topic%/SHUTTER {"Shutter1":{"Position":%var1%,"Direction":%var2%,"Target":%value%}}
```
That would republish any Shutter data in a tele/%topic/SENSOR message to stat/%topic/SHUTTER

**Reply by ma-zal** [reply]
> If somebody writes to "cmnd/tasmotas/SHUTTER" it send the SHUTTER command to all tasmotas

Answer: My bad. Copy-paste issue, when I created comment. :) Of course, I wanted to write topic to my `tasmota_tx1`, not to whole group `tasmotas`. Thanks for notice.

**Reply by ma-zal** [reply]
> I was meaning a Rule on the tasmota device such as

This is great idea. I did not consider to republish MQTT message directly in Tasmota by rule. This perfectly helps. So THREAD SOLVED.

Just small fix for others, who wants to also use your example - there is what exactly to enter to Tasmota console:

```
SetOption4 1
rule1 on tele-Shutter1#Position do var1 %value% endon on tele-Shutter1#Direction do var2 %value% endon on tele-Shutter1#Target do publish stat/%topic%/SHUTTER {"Shutter1":{"Position":%var1%,"Direction":%var2%,"Target":%value%}} endon
rule 1 1
```

Used HASS configuration: [Integration example with position updated during movement](https://tasmota.github.io/docs/Home-Assistant/#device-specific). But change original `position_topic` to `position_topic: "stat/%topic%/SHUTTER"`

**Comment by TrDA-hab** [comment, marked as answer]
For my purposes, everything works great!
![Снимок экрана 2021-04-13 в 11 58 59](https://user-images.githubusercontent.com/56403720/114526486-b4869380-9c4f-11eb-8f55-06ccdc4921e9.png)

https://user-images.githubusercontent.com/56403720/114525977-3de99600-9c4f-11eb-98de-a89e93605db3.mp4

**Reply by TrDA-hab** [reply]
```yaml
type: entities
title: Livingroom blinds
entities:
  - cover.blinds_1
  - type: 'custom:slider-entity-row'
    entity: cover.blinds_1
    name: Open1%
  - type: 'custom:cover-position-preset-row'
    name: Position1
    entity: cover.blinds_1
    reverseButtons: false
    customSetpoints: true
    closePosition: 0
    midClosePosition: 25
    midOpenPosition: 65
    openPosition: 100
  - type: divider  
  - cover.blinds_2
  - type: 'custom:slider-entity-row'
    entity: cover.blinds_2
    name: Open2%
  - type: 'custom:cover-position-preset-row'
    name: Position2
    entity: cover.blinds_2
    reverseButtons: false
    customSetpoints: true
    closePosition: 0
    midClosePosition: 25
    midOpenPosition: 65
    openPosition: 100
```
Additional information (see example for Covers).
https://tasmota.github.io/docs/Home-Assistant/#device-specific
