### DISCUSSION TITLE
How to set shutter 1 and shutter 2 cover with sonoff 4CHPRO on home assistant

### DISCUSSION THREAD

**Discussion by manny199** [arendst/Tasmota#12538] [Q&A] [answered]
Hello,
I have one Sonoff 4CHPRO2 for two shutters.
Please tell me how set cover to use shutter 1 and shutter 2 on Home Assistant.

In my configuration.yaml I create this cover but work with one shutter:

```
############# SHUTTER 1 #####################
- platform: mqtt
  name: "Tapp 1"
  availability_topic: "tele/sonoff4pro2/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  command_topic: "cmnd/sonoff4pro2/Backlog"
  payload_open: "ShutterOpen1"
  payload_close: "ShutterClose1"
  payload_stop: "ShutterStop1"
  set_position_topic: 'cmnd/sonoff4pro2/ShutterPosition1'
  position_topic: "stat/sonoff4pro2/RESULT"
  position_open: 100
  position_closed: 0
  position_template: >
    {% if ('Shutter1' in value_json) and ('Position' in value_json.Shutter1) %}
      {{ value_json.Shutter1.Position }}
    {% else %}
      {% if is_state('cover.test', 'unknown') %}
        50
      {% else %}
        {{ state_attr('cover.test','current_position') }}
      {% endif %}
    {% endif %}
  retain: false
  optimistic: false
  qos: 1

############# SETTING FOR SHUTTER 2 ???? #####################

```
Thank you

**Comment by TrDA-hab** [comment, marked as answer]
Create settings for shutter 2. For myself, I did this:

```yaml
# Livingroom Blinds
cover:
  - platform: mqtt
    name: "Blinds 1"
    availability_topic: "tele/Roll_3/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    position_topic: "stat/Roll_3/RESULT"
    value_template: >
      {% if ('Shutter1' in value_json) and ('Position' in value_json.Shutter1) %}
        {{ value_json.Shutter1.Position }}
      {% else %}
        {% if is_state('cover.livingroom_blinds1', 'unknown') %}
          50
        {% else %}
          {{ state_attr('cover.livingroom_blinds1','current_position') }}
        {% endif %}
      {% endif %}    
    position_open: 100
    position_closed: 0
    set_position_topic: "cmnd/Roll_3/ShutterPosition1"
    command_topic: "cmnd/Roll_3/Backlog"
    payload_open: "ShutterOpen1"
    payload_close: "ShutterClose1"
    payload_stop: "ShutterStop1"
    retain: false
    optimistic: false
    qos: 1
  - platform: mqtt
    name: "Blinds 2"
    availability_topic: "tele/Roll_3/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    position_topic: "stat/Roll_3/RESULT"
    value_template: >
      {% if ('Shutter2' in value_json) and ('Position' in value_json.Shutter2) %}
        {{ value_json.Shutter2.Position }}
      {% else %}
        {% if is_state('cover.livingroom_blinds2', 'unknown') %}
          50
        {% else %}
          {{ state_attr('cover.livingroom_blinds2','current_position') }}
        {% endif %}
      {% endif %}    
    position_open: 100
    position_closed: 0
    set_position_topic: "cmnd/Roll_3/ShutterPosition2"
    command_topic: "cmnd/Roll_3/Backlog"
    payload_open: "ShutterOpen2"
    payload_close: "ShutterClose2"
    payload_stop: "ShutterStop2"
    retain: false
    optimistic: false
    qos: 1

```

https://user-images.githubusercontent.com/56403720/124360361-0aa51a80-dc32-11eb-8161-4001462915e2.mp4
