### DISCUSSION TITLE
Link switch to relay when no connection

### DISCUSSION THREAD

**Discussion by AndreKR** [arendst/Tasmota#14654] [Q&A] [answered]
I have a Shelly 1 with a switch input connected via MQTT to Home Assistant.

As long as Home Assistant is available, the switch should be detached and Home Assistant should control the relay.

However, if Home Assistant becomes unavailable, I'd like Tasmota to turn on the relay whenever the switch turns on. Keep it on until the switch turns off or until PulseTime is over, either way is fine.

(I don't think there is a way to detect a failed *Home Assistant* in particular, so we can assume if Home Assistant fails, the MQTT broker fails as well.)

**Comment by pkkrusty** [comment]
What if you create a virtual relay on the Shelly with a 60 second pulsetime, and have HomeAssistant turn it on every 59 seconds. Then make a rule `on power2=0 do switchmode1 0 endon on power2=1 do switchmode1 15 endon`

Should be a one-shot rule I think.

**Reply by barbudor** [reply]
How are you achieving "a switch input connected via MQTT to Home Assistant." ?
It seems that SwitchTopic may help
https://tasmota.github.io/docs/Buttons-and-Switches/#switchtopic

**Comment by AndreKR** [comment, marked as answer]
Following @barbudor's comment I achieved it like this:

* First configure the device in the way it should work when there's no MQTT connection.
* Go to Configuration -> Configure MQTT.
* Copy the Topic ("tasmota_XXXXXX").
* Run `SwitchTopic tasmota_XXXXXX_sw` (change "sw" to your liking)
* In Home Assistant (unfortunately this requires editing the configuration on the host and restarting Home Assistant) add this to `configuration.yaml`:
```yaml
binary_sensor:
  - platform: mqtt
    name: "The Switch Input"
    state_topic: "cmnd/tasmota_XXXXXX_sw/POWER1"
    availability_topic: "tele/tasmota_XXXXXX/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: "motion" # If you want to use this input with motion-activation blueprints
```
