### DISCUSSION TITLE
Rate limiting for MQTT?

### DISCUSSION THREAD

**Discussion by FrenkK** [arendst/Tasmota#14842] [Q&A] [answered]
I hacked a Tuya Smart Air by unsoldering their WiFi chip and soldering in a Wemos D1 with Tasmota flashed. The Tuya MCU module decodes the sensor data and it works.
The problem is, the updates are coming every second or even more frequently and this is bogging down my Homeassistant installation. Is there any way to simply send the MQTT update with the the last received value for all the sensors every minute or so? Having the option to average the values in between would be even nicer, the sensor data are noisy.

**Comment by FrenkK** [comment]
I solved this by going the other way. I used the Tasmota REST API to set up RESTful sensors in Home Assistant where I can set the scan interval.
This is the HA config that works for me:
```
rest:
  - scan_interval: 60
    resource: http://airdnevna.fritz.box/cm?cmnd=Status%2010
    sensor:
    - name: dnevna_humidity
      value_template: "{{value_json['StatusSNS']['TuyaSNS'].Humidity}}"
      unit_of_measurement: "%"
    - name: dnevna_TVOC
      value_template: "{{value_json['StatusSNS']['TuyaSNS'].TVOC }}"
      unit_of_measurement: "ppm"
    - name: dnevna_particulates
      value_template: "{% set particulates = value_json['StatusSNS']['TuyaSNS'].Illuminance %}{% if particulates > 0 and particulates <10000 %} {{particulates}} {%else%} {{0 | float}} {%endif%}"
      unit_of_measurement: "ug/m3"
  - scan_interval: 60
    resource: http://airpisarna.fritz.box/cm?cmnd=Status%2010
    sensor:
    - name: pisarna_humidity
      value_template: "{{value_json['StatusSNS']['TuyaSNS'].Humidity}}"
      unit_of_measurement: "%"
    - name: pisarna_TVOC
      value_template: "{{value_json['StatusSNS']['TuyaSNS'].TVOC }}"
      unit_of_measurement: "ppm"
    - name: pisarna_particulates
      value_template: "{% set particulates = value_json['StatusSNS']['TuyaSNS'].Illuminance %}{% if particulates > 0 and particulates <10000 %} {{particulates}} {%else%} {{0 | float}} {%endif%}"
      unit_of_measurement: "ug/m3"
```
Still, it would be good to have a MQTT-related solution too.
