### DISCUSSION TITLE
Support for Hiking DDS-238-2 wifi energy meter

### DISCUSSION THREAD

**Discussion by davoau** [arendst/Tasmota#15643] [Ideas]
Hi,
I have a Hiking DDS-238-2 wifi energy meter.  I have use this (https://github.com/krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota) to set it up. It works for reporting energy used - eg for hotwater cylinder, however I am lacking the reverse energy readings so that I can see what is being exported to the grid from my solar system.

The reverse energy kWh's can be viewed on the LCD display of the meter, and ESPHome can report them so this (https://www.esphome-devices.com/devices/Hiking-DDS238-2-WIFI). post says.

I use the following console command to get it to report power, current, voltage and +kWh:
```
Backlog TuyaMCU 33,20; TuyaMCU 32,18; TuyaMCU 31,19; TuyaMCU 37,101;
```

In esphome they have the below if get positive and reverse energy reported:
```
  - platform: "tuya"
    name: "${friendly_name} kWh +"
    sensor_datapoint: 101
    unit_of_measurement: "kWh"
    accuracy_decimals: 3
    icon: "mdi:flash"
    filters:
      - multiply: 0.01

  - platform: "tuya"
    name: "${friendly_name} kWh -"
    sensor_datapoint: 9
    unit_of_measurement: "kWh"
    accuracy_decimals: 3
    icon: "mdi:flash"
    filters:
      - multiply: 0.01
```

Is it possible to get the reverse energy data using datapoint 9 in tasmota, and if so how and what is the function ID for dpID9 ?
Thanks
