### DISCUSSION TITLE
2 Channel relay with MQTT config

### DISCUSSION THREAD

**Discussion by n00bster-za** [arendst/Tasmota#15657] [Q&A] [answered]
any MQTT experts that can help me please. I have flashed a 2 Channel Relay with Tasmota and now want to use the GPIO14 with a door contact to read the status of the gate. 

I have seen some videos on the MQTT topics but don't think they apply to my config since I have 2 relays and want to use the GPOI14 as switch.

any one that can help with the correct MQTT setting to make sure the switch is separate from the relays? and what the config will look like to add it on a card. Already have the 2 Relays sorted and in HA.

I have used retain topics and use retain power. I need help to make sure the switch topic is correct and won't trigger relay 1 or 2 and the add the config to a card.

**Comment by barbudor** [comment, marked as answer]
Please read the doc section https://tasmota.github.io/docs/Buttons-and-Switches/#ac-frequency-detection-switch
About the 3 methods to detach switches from relays
One of the 3 will suit your need. Most likely 'switchmode 15' or 'setoption114'
In addition you can use 'SwitchText1 Door' to rename the key reported in the json

**Comment by n00bster-za** [comment]
thanks I have changed some of the MQTT settings according to the documentation you linked me to. When connecting to MQTT explorer connecting to my HA and cant see the state topic though. I still only see the 2 relay topics. is this because the switch has not been triggered yet?

**Reply by barbudor** [reply]
I have no knowledge of HA but my understanding is that switches as binary sensors have to be manually integrated.

**Comment by n00bster-za** [comment]
okay so in the Tasmota console if I use a door contact on GPIO14 I should see the topics come up if I open and close the contact?

**Reply by barbudor** [reply]
If you followed one of the method described you should see the corresponding messages

**Comment by n00bster-za** [comment]
So i have done some configs but I cannot see anything happening when I open and close the door contact. 

I tested the ground and GPIO14 and I am getting the 3.3v but when I connect the door contact to it. and manually open and close the magnet I see no info on the Tasmota console.  

what am I doing wrong. 

the below is what I get when I trigger the relay 1 and 2. Maybe my topics are not correct? Just dont see anything from the Switch 2 which is GPIO14

10:18:24.319 MQT: Gate/stat/RESULT = {"POWER2":"ON"}
10:18:24.322 MQT: Gate/stat/POWER2 = ON (retained)
10:18:24.870 MQT: Gate/stat/RESULT = {"POWER2":"OFF"}
10:18:24.872 MQT: Gate/stat/POWER2 = OFF (retained)
10:18:28.911 MQT: Gate/stat/RESULT = {"POWER1":"ON"}
10:18:28.916 MQT: Gate/stat/POWER1 = ON (retained)
10:18:29.462 MQT: Gate/stat/RESULT = {"POWER1":"OFF"}
10:18:29.467 MQT: Gate/stat/POWER1 = OFF (retained)

**Comment by n00bster-za** [comment]
So I found this repository below.

https://github.com/blakadder/templates/blob/master/_templates/eachen_ST-DC2

I have added this as my template but now I have 4 toggles instead of 2. Is this correct? now GPIO14 is set as Switch4. But I still can see any info in the console when opening\Closing the contact. (Grounding the GPIO14 pin)

**Reply by barbudor** [reply]
Without you explicitly giving all details ont what you have done, we can't help you

**Comment by n00bster-za** [comment]
okay I got it working with the below code. Managed to get the corect pin and get the switch configured. Now I just want to get it a better looking card. Is there a way to let the whole Card change color based on status?

```
cover:
  - platform: mqtt
    name: "Gate 1"
    state_topic: cmnd/gatestatus/POWER2
    command_topic: cmnd/gate/Power1
    availability_topic: tele/gate/LWT
    payload_open: "ON"
    payload_close: "ON"
    payload_stop: "ON"
    state_open: "OFF"
    state_closed: "ON"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    qos: 0
    retain: false
  - platform: mqtt
    name: "Gate 2"
    state_topic: cmnd/gatestatus/POWER2
    command_topic: cmnd/gate/Power2
    availability_topic: tele/gate/LWT
    payload_open: "ON"
    payload_close: "ON"
    payload_stop: "ON"
    state_open: "OFF"
    state_closed: "ON"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    qos: 0
    retain: false
```
