### DISCUSSION TITLE
Sonoff SwitchMan M5 Ledlink_i

### DISCUSSION THREAD

**Discussion by Garreth2013** [arendst/Tasmota#15757] [Q&A] [answered]
Ive installed a bunch of the new Sonoff M5, used Blackadder template. Running Tasmota 11.1.0 
The 3 gang switch works flawlessly. 
The 2 gang and 1 gang relay and button works fine. 
The Link Led's for the 1 gang and 2gang do not. The RED Led only works on Relay 1, not relay 2. The Blue LED works as expected.
Ive applied the 3 gang to the 2 gang to ensure the LED works. When software switching relay 3 on, the red LED lights up on button 2. Almost like red LED for relay 3 is used on the 2 gang for relay 2. Same for the 1 gang switch. 

LedLink_i is mapping LED to relay 2, but on the M5 2gang and 1 gang it seams the LED is mapped to button 3.

**Comment by arendst** [comment]
From your description I suppose the templates for your M5 2 gang and 1 gang switches are wrong.

You'll need to experiment with them to find the correct GPIOs for the correct loads.

**Reply by Minkoley** [reply]
@Garreth2013 
I got the same "issue". Have you already found the correct GPIOs for the 2 gang?

**Comment by Garreth2013** [comment, marked as answer]
Hi Tommy, not as yet, haven’t had a chance to do the work, Ill give it a proper go on the weekend. I removed the LedLink(i) and tried to add them manually to empty GPIO’s but still stuck with the Led on the second switch wired to the 3rd relay. Would need to map the 2nd and 3rd relay as relay 2 and apply the LED to the 3rd that and also check all GPIO’s for correct mapping.

**Reply by Garreth2013** [reply]
Did some work on it, GPIO22 is the LED for switch 2, but wired to relay 3 output. Even if I set GPIO22 as LED2 etc it does not work. Only works when I set it as Relay output. Ive just setup a template in Home assistant to switch on/off the LED when the relay 2 goes off/on. Im sure this could also be achieved using groups in Tasmota.

**Reply by Minkoley** [reply]
That helps a lot. I also using HomeAssistant so I will do the same. Thank you!

**Reply by Minkoley** [reply]
I now use a rule to control the LED. Prerequisite is the configuration of the GPIO22 as relay 4.
```
rule1 on power2#state do power4 %value% endon 
rule1 1
```

**Reply by gettingerr** [reply]
Nibbler you are an absolute legend. Your solution plus the rule is working perfectly in Tasmota for me. Do you by chance know how I would write this rule in ESPHome?

EDIT: Turns out I'm not as dumb as I thought. See below for the ESPHome solution for a 1-gang switch to get the light coupled. Should similarly work with a 2-gang assuming pins are adjusted properly:

```
switch:
  - platform: gpio
    id: relay_1
    name: "Kitchen Sink"
    pin: 23
    on_turn_on:
      - light.turn_on: led1
    on_turn_off:
      - light.turn_off: led1
    
output:
  - platform: ledc
    pin: 18
    frequency: 1000 Hz
    id: pwm_output
  - platform: gpio
    id: relay_4
    pin: 19
    
light:
  - platform: monochromatic
    output: pwm_output
    name: "LEDs"
  - platform: status_led
    name: "Network Status"
    pin:
      number: 5
      inverted: true
  - platform: binary
    id: led1
    name: "LED 1"
    output: relay_4

binary_sensor:
  - platform: gpio
    id: kitchen_sink
    pin:
      number: 0
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: relay_1
```

All credit to Nibbler for turning me on to this solution. Feel free to DM me for the 2-gang code if you need help.

**Comment by madrose** [comment]
I also have the same issue. the template is still wrong for the 1 gang and 2 gang.

**Reply by gettingerr** [reply]
2 gang:

esphome:
  name: sonoff-bathroom-sink

esp32:
  board: esp32dev
  framework:
    type: arduino


logger:


api:
  encryption:
    key: 

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


  ap:
    ssid: "Sonoff-Bathroom-Sink"
    password: 

captive_portal:
    
    
switch:
  - platform: gpio
    id: relay_1
    name: "Bathroom Sink Top"
    pin: 23
  - platform: gpio
    id: relay_2
    pin: 19
    name: "Bathroom Sink Bottom"
    on_turn_on:
      - light.turn_on: led2
    on_turn_off:
      - light.turn_off: led2

output:
  - platform: ledc
    pin: 18
    frequency: 1000 Hz
    id: pwm_output
  - platform: gpio
    id: relay_4
    pin: 22
    
light:
  - platform: monochromatic
    output: pwm_output
    name: "LEDs"
  - platform: status_led
    name: "Network Status"
    pin:
      number: 5
      inverted: true
  - platform: binary
    id: led2
    name: "LED 2"
    output: relay_4
    
binary_sensor:
  - platform: gpio
    id: bathroom_sink_top
    pin:
      number: 4
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: relay_1
  - platform: gpio
    id: bathroom_sink_bottom
    pin:
      number: 15
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: relay_2



1 gang:

esphome:
  name: sonoff-guest-hall-lr

esp32:
  board: esp32dev
  framework:
    type: arduino


http_request:
  useragent: esphome/guest-hall-lr
  timeout: 10s
  id: guest_hall_lr_http
  

logger:

api:
  encryption:
    key: ""


ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

 
  ap:
    ssid: "Sonoff-Guest-Hall-Lr"
    password: ""

web_server:
  port: 80

captive_portal:
    
    
    
switch:
  - platform: gpio
    id: relay_1
    name: "Guest Hall LR"
    pin: 23
    on_turn_on:
      - light.turn_on: led1
    on_turn_off:
      - light.turn_off: led1

      
output:
  - platform: ledc
    pin: 18
    frequency: 1000 Hz
    id: pwm_output
  - platform: gpio
    id: relay_4
    pin: 19
    
light:
  - platform: monochromatic
    output: pwm_output
    name: "LEDs"
  - platform: status_led
    name: "Network Status"
    pin:
      number: 5
      inverted: true
  - platform: binary
    id: led1
    name: "LED 1"
    output: relay_4

binary_sensor:
  - platform: gpio
    id: guest_hall_lr
    pin:
      number: 0
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: relay_1

**Reply by gettingerr** [reply]
Sorry it's not code formatted. Too stupid to figure it out on my phone

**Comment by donotoverdriveit** [comment]
Hello, are there any new solutions to the LED problem for the second relay (dual switch)?

If not, how exactly do I apply all the text code in Tasmota? I suspect something under "Manage File System"? Does the file name have to have a specific name and file extension?

**Reply by gettingerr** [reply]
Here's the important setup items for my ESPHome config for 2 button switches. This same info is right above your post for 1 gang and 2 gang. Tasmota is possible but I found much easier in ESPhome

```
captive_portal:
    
    
switch:
  - platform: gpio
    id: relay_1
    name: "Bathroom Sink Top"
    pin: 23
  - platform: gpio
    id: relay_2
    pin: 19
    name: "Bathroom Sink Bottom"
    on_turn_on:
      - light.turn_on: led2
    on_turn_off:
      - light.turn_off: led2

output:
  - platform: ledc
    pin: 18
    frequency: 1000 Hz
    id: pwm_output
  - platform: gpio
    id: relay_4
    pin: 22
    
light:
  - platform: monochromatic
    output: pwm_output
    name: "LEDs"
  - platform: status_led
    name: "Network Status"
    pin:
      number: 5
      inverted: true
  - platform: binary
    id: led2
    name: "LED 2"
    output: relay_4
    
binary_sensor:
  - platform: gpio
    id: bathroom_sink_top
    pin:
      number: 4
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: relay_1
  - platform: gpio
    id: bathroom_sink_bottom
    pin:
      number: 15
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: relay_2
```
