### DISCUSSION TITLE
Sonoff SA-018 switch does not work

### DISCUSSION THREAD

**Discussion by anti-social** [arendst/Tasmota#15777] [Q&A] [answered]
Have a  Sonoff SA-018 relay (like Sonoff Mini but works without a neutral wire). Found a template for it here: https://templates.blakadder.com/SA-018.html
The relay works fine with the template but the switch does not. Tried all available `GPIO` pins to set either `Switch` or `Switch_n` but with no luck.

With original firmware the switch worked fine.

May be someone have experience how to setup this device?

**Comment by sfromis** [comment]
That thing is not from Sonoff (eWeLink does not mean Sonoff), and I have no experience with it.

Please be more specific about details, like how you connected exact wiring, or if you mean the "Wifi Pairing Button" on the board? In principle, the analog pin could also be used for a switch input, but that's not very common.

**Reply by sfromis** [reply]
I don't know the background, but the Mediarath page has a strong warning, suggesting that it may cause problems to not follow the exact steps.... Wondering if they mean hardware damage?

**Please leave the device switched off before installation. Do not start the installation process when the power is on. Connect the capacitor (included) to the neutral wire first and only then connect the other terminals to the switching module. Only when the entire connection of the module has been completed may the power be switched on.**

**Reply by anti-social** [reply]
I wired it according to the manual. And it worked fine with an original firmware. And the relay works with Tasmota. I can turn it on/off via my home assistant installation. But switch button does nothing.

Also there is a pairing button on the board and it toggles the relay (using this button I could toggle the device into DIY mode and flash Tasmota over the air).

**Comment by anti-social** [comment, marked as answer]
I flashed [ESP HomeKit](https://github.com/RavenSystem/esp-homekit-devices) firmware, applied a [configuration](https://github.com/RavenSystem/esp-homekit-devices/issues/1334#issuecomment-779905898) and the switch is working at the moment.

Applied configuration looks like:
```json
{
  "c":{"l":13,"b":[{"g":0,"t":5}]},
  "a":[
    {
      "0":{"r":[{"g":12}]},
      "1":{"r":[{"g":12,"v":1}]},
      "b":[
        {"g":0},
        {"g":4},
        {"g":4,"t":0}
      ]
    }
  ]
}
```

And its [explanation](https://github.com/RavenSystem/esp-homekit-devices/wiki/Accessory-Configuration).

Still don't know what is wrong with the Tasmota configuration.

**Reply by sfromis** [reply]
Since "b" means binary inputs and "g" then means gpio, this indicates that gpio0 and gpio4 are relevant, while gpio12 is the relay output. As the Tasmota template already defines gpio4 and 12, that means that you need to configure gpio0 to match hardware behavior. If you temporarily unconfigure gpio 4 (to make it as simple as possible), and configure gpio0 as a Switch, any action on that pin should manifest in what happens on the relay.

**Reply by anti-social** [reply]
Now I need to flash Tasmota again but I don't know if it is possible to do over the air.

**Reply by sfromis** [reply]
Never having used that ESP HomeKit thing, I do not know either, but unless you quickly spot a good place to try, the fastest may just be to do wired flashing again.

When you have gotten it to work, please update the Tasmota template to a working setup.

**Reply by anti-social** [reply]
I've managed to flash tasmota firmware again.But I can't make it work as it's expected.

Gpio0 button toggles relay even if it's not configured at all. Led also shines without any configuration. I tried all the button and switch variants for gpio0 and gpio4 pins without success. Don't have any ideas what cant I try to test

**Reply by anti-social** [reply]
It works! I don't understand how tasmota configuration exactly works, but if I setup `Switch` entry on `GPIO4` via "Configure Module" menu item the device begins  to work as expected.

**Reply by anti-social** [reply]
Need to read a documentation to understand how it works.

**Reply by sfromis** [reply]
Default config is to work as a Sonoff Basic unless you did something different, like configuring the device template from https://templates.blakadder.com/SA-018.html
That default has a button on gpio0, relay on gpio12 and a led on gpio13. When it is allowed to be a "Sonoff Basic", what you do in "Configure Module" is only adding to that.
In general, things gets more straightforward if you use Module 18 (Generic) to configure your pin setup, or do it all in a template.

**Reply by anti-social** [reply]
Thanx for your help.

**Comment by ferbulous** [comment]
Hello, I have the same issue with buttons not working
I've tried setting gpio00 & gpio04 as button/switch vice versa but I'm not able to get the physical button toggle working
I ended up using esphome, and it worked for me with the same gpio pin listed
Could anyone clarify how I should set gpio00 & gpio04 based on this esphome config?

```
substitutions:
  device_name: XXXXXXX_led
  device_ip: 192.168.XX.XX
  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: "XXXXXXXXXXXXXXXX"
  password: "XXXXXXXXXXXXXXX"
  manual_ip:
    static_ip:  ${device_ip}
    gateway: 192.168.0.254
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sonoff ledHotspot"
    password: "XXXXXXXXXXXXXXX"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: ${device_name} Wifi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: ${device_name} Uptime
#######################################
# Device specific Config Begins Below #
#######################################

binary_sensor:
  # the 7 lines below define the reset button
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true  # hides reset switch from HomeAssistant
    filters:
      - invert:
      - delayed_off: 10ms
  # the 3 lines below toggle the main relay on press of reset button
    on_press:
      - light.toggle:
          id: light_id

  # the 13 lines below toggle the main relay on command
  - platform: gpio
    name: relay_toggle
    #internal: true  # hides relay toggle from HomeAssistant
    pin: GPIO04
    id: gpio_light_id
    on_press:
      then:
        - light.toggle:
            id: light_id
    on_release:
      then:
        - light.toggle:
            id: light_id

  # the 2 lines below create a status entity in HomeAssistant.
  - platform: status
    name: ${device_name} Status

status_led:
  pin:
    number: GPIO13
    inverted: true

output:
  # the 3 lines below control the main relay
  - platform: gpio
    pin: GPIO12
    id: main_light_relay  
  # the 3 lines below control the Blue LED
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  # the 4 lines below define the main relay as a light
  - platform: binary
    name: ${device_name}_light # you can enter a custom name to appear in HomeAsistant here.
    output: main_light_relay  
    id: light_id
  # the 4 lines below define the Blue LED light on Sonoff Mini, to expose in HomeAssistant remove line "internal: true"
  - platform: monochromatic
    name: ${device_name}_blueled
    output: blue_led
    internal: true # hides the Blue LED from Homeassistant
````
