### DISCUSSION TITLE
New Shelly Pro Series (i.e. 2/2PM)

### DISCUSSION THREAD

**Discussion by Mark-Muc** [arendst/Tasmota#16733] [General]
Hello .. is it possible / planed to suppoert these devices?? 
Shelly Pro Series (i.e. 2/2PM)
In the version "[12.1.1.4] Support for Shelly Plus 2PM using template" 
is integrated ..
Thx for any answer!!
Mark

**Comment by barbudor** [comment]
What answer ?
You already found that it is supported with the given template

**Comment by Mark-Muc** [comment]
I am asking for Shelly **PRO** series... like
https://www.shelly-smarthome-shop.de/smarte-relais/pro-line/11153/shelly-pro-2

In version 12.1.1.4 support for Shelly **PLUS** was built in ... like
https://www.shelly-smarthome-shop.de/smarte-relais/plus-serie/11237/shelly-shelly-plus-2pm?number=Shelly-ShellyPlus2PM

**Reply by barbudor** [reply]
It needs someone to have its hand on the unit and open it to check what is inside
Can you do it ?
Most likely the Pro is just a Plus in a DIN box

**Comment by Mark-Muc** [comment]
i ordered one today .. will arrive these days .. I'll try to open it and make some pic's!!
But I don't think so, .. it is complete different layout AND the PRO Series also have LAN (RJ45) & WiFI

**Reply by sfromis** [reply]
ESPHome already has a setup for [Shelly Pro 1](https://www.esphome-devices.com/devices/Shelly-Pro-1) which may have significant similarities even if not the same device, but still including Ethernet support (diagnosed as LAN8720A even if ESPHome does not seem to support this).

The oddity (Shelly likes making things "different" without obvious reason) is that the relay and leds are driven via a SN74HC595B shift register instead of just being hooked directly up to ESP32 pins. Go figure :wink: 

If the Shelly Pro 2 devices work the same way, the shift register needs setup, but that may not be too bad as Tasmota already has Shift595 support.

**Reply by barbudor** [reply]
What ?!
Why bothering using an '595 on a ESP32 where you have plenty of pins.
The good news is that we have a driver for the '595 thanks to Faz learning C 🤣

**Reply by sfromis** [reply]
If I try to invent a reason, the shift register chip may be more robust when it comes to leds drawing power, and maybe even the relay. Pure uninformed speculation of course :see_no_evil: 

We even have shift register support in Berry too...

**Comment by Mark-Muc** [comment]
any news on that? I today got the Shelly 2 pro (without power monitoring) .. how to falsh and config ..
Thanks again
Mark

**Reply by barbudor** [reply]
Any news on what? 

Did you opened it and searched for the details?
You are the one with the unit in hands

**Reply by sfromis** [reply]
Flashing and configuration is likely pretty similar to doing it for the Shelly Pro 1, where I linked to what ESPHome has. That gives you something to work with, and then *you* can submit a Tasmota template when you get it complete for the two-channel model.

**Reply by Mark-Muc** [reply]
tomorrow i'd like to open the "damed" thing .. didn't find any hint to OPEN it!!
Mark

**Reply by sfromis** [reply]
Assuming that it is similar to the Shelly Pro 1, you do not need to open it to flash firmware, as the usual connector should be available from the side, with pinout here:
https://www.esphome-devices.com/devices/Shelly-Pro-1#programming-pinout
If the assumed shift register is on the same pins, that setup should get you a long way.

**Reply by Mark-Muc** [reply]
@sfromis Many thanks for your help .. 
I found the connector and have cable .. so it shoud work ..
BUT witch version should I compile? "solo1" as it is on a shelly plus 2??
What to include, to have the shiftregister (SN74HC595B ) available to select or is it in the "standard" edition?
I'll play this week...
Thanks & Regards 
Mark

**Reply by sfromis** [reply]
I just do not know which MCU is in there, esptool.py can tell you something with the flash_id subcommand, but the solo1 build works even if not single core; not the other way around. For normal Tasmota usage, building for dual core really does not give any benefit, anyway.

Shift595 support is included build time setting `USE_SHIFT595`, and then config the relevant pins as usual.

**Comment by Mark-Muc** [comment]
OK I will built simply a "solo1" version with USE_SHIFT595..
on the ESPHome link i found:

```
sn74hc595:
  - id: 'sn74hc595_hub'
    data_pin: GPIO13
    clock_pin: GPIO14
    latch_pin: GPIO4
    sr_count: 1

switch:
  - platform: gpio
    name: "Shelly Pro Relay"
    id: light1
    pin:
      sn74hc595: sn74hc595_hub
      number: 0
      inverted: false

  - platform: gpio
    id: out2
    pin:
      sn74hc595: sn74hc595_hub
      number: 1
      inverted: false

  - platform: gpio
    id: rgb_b
    pin:
      sn74hc595: sn74hc595_hub
      number: 2
      inverted: false

  - platform: gpio
    id: rgb_g
    pin:
      sn74hc595: sn74hc595_hub
      number: 3
      inverted: false

  - platform: gpio
    id: rgb_r
    pin:
      sn74hc595: sn74hc595_hub
      number: 4
      inverted: false

```
OK i am not so "experiences" but I will try 
what i don't know ist how to configure     `sr_count: 1` in Tasmota
I am sure it comes to thousands of questions ..
I hope I am not too annoying and you help me here further.
Regards 
Mark
