### DISCUSSION TITLE
ENS160 sensor implementation

### DISCUSSION THREAD

**Discussion by Westeru** [arendst/Tasmota#16983] [Ideas]
I discovered and bought a gas sensor for CO2 but i noticed that it is not implemented in Tasmota and i wonder if anyone is willing to give it a try and implement it. 
I found some driver on git from DFRobot but it is waaay over my head to do this my self because i dont know if anything has to be modify or not. 
https://github.com/DFRobot/DFRobot_ENS160
The board that i got is acually a combo one with ENS160+AHT21 - https://www.aliexpress.com/item/1005004052950350.html

**Comment by s-hadinger** [comment]
This looks like classical I2C protocol so quite easy to adapt, especially on Esp32 using a driver written in Berry. 

Is it a good sensor? I might be interested as well in buying those and implementing the driver

**Reply by Westeru** [reply]
I don't know if the sensor is good or not because I didn't had the chance to test it due to lack of implementation in Tasmota.

**Reply by sfromis** [reply]
I tend to be skeptical of those VOC sensors claiming to be CO2 sensors. The usual tin oxide principle cannot measure CO2 as such, only having the resistance varying with the combination of humidity, temperature, various VOC, CO2 and time. While the separate temp/hum sensor helps, guessing at what's in the air has to assume other factors being stable or known. Using the term "eCO2" basically means "not CO2" :wink:

**Reply by s-hadinger** [reply]
Thanks for the details. Any advice on a real CO2 sensor?

**Reply by arendst** [reply]
Scd30

**Reply by sfromis** [reply]
I'm using the successor, SCD40

**Comment by NonaSuomy** [comment]
You can use this in ESPHome currently from a PR if you want to test it out. I have it currently running on my iFan04 working good so far.
![00CEC774-5870-4141-B511-4B947670B335](https://user-images.githubusercontent.com/1906575/217464198-38c31847-55e4-4493-86d9-ab6da4a71098.jpeg)
![85182398-8DC1-4638-B66C-BDD67A81DC54](https://user-images.githubusercontent.com/1906575/217464203-724b92cc-deae-44d3-946e-1f49750dccf7.jpeg)

![F9471C3A-6983-4383-BBF7-E3A1660DE123](https://user-images.githubusercontent.com/1906575/217463868-e32621fc-efb3-4992-9cf3-4ca5097b342a.jpeg)

```yaml 
# ENS160 + AHT21 Module https://www.aliexpress.us/item/3256804712105923.html

# Define the I2C device for iFan04 to the Test Points on the back of the board.
# GPIO04 - TP11 D_RX (SDA)
# GPIO05 - TP10 D_TX (SCL)
i2c:
  id: i2c_component
  sda: 4
  scl: 5
  scan: true

external_components:
  - source: github://pr#4243
    components:
      - ens160

sensor:
  - platform: aht10
    id: aht21_sensor
    address: 0x38
    temperature:
      name: "AHT21 Sensor Temperature"
      id: aht21_sensor_temp
    humidity:
      name: "AHT21 Sensor Humidity"
      id: aht21_sensor_humi
    update_interval: 55s

  - platform: ens160
    id: ens160_sensor
    address: 0x53
    eco2:
      name: "ENS160 Sensor eCO2"
      id: ens160_sensor_eco2
    tvoc:
      name: "ENS160 Sensor Total Volatile Organic Compounds"
      id: ens160_sensor_tvoc
    aqi:
      name: "ENS160 Sensor Air Quality Index"
      id: ens160_sensor_aqi
    # Inject the temp/humi data from the AHT21 into the ENS160 attached module for compensation.
    # Makes the gas results more accurate.
    temperature: aht21_sensor_temp
    humidity: aht21_sensor_humi
    update_interval: 60s
```
