### DISCUSSION TITLE
Modification for Switchmode 11

### DISCUSSION THREAD

**Discussion by pimw1** [arendst/Tasmota#18047] [Ideas]
Hi, i'd like to modify switchmode 11. Switchmode 11 is creating switch1#state=2 on a single press, repeatingly switch1#state=4  on a long press, and switch1#state=7 after releasing a long press.

I'd like to use switch1#state=4 to start a dimmer increase (Dimmer >), and switch1#state=7 to stop the dimming (Dimmer !).
However, because switch1#state=4 is happening a couple of times per second (while holding down the button), the "Dimmer >" command is triggered many times. This results in less smooth dimming. From my own testing, i can see that the dimming is much smoother if the "Dimmer >"  command is only provided once.

Therefore, i am looking for a modification of switchmode 11: switch1#state=4 only firing once while holding down the button. Would that be possible?

**Comment by barbudor** [comment]
The goal of 4 is to trigger a Dimmer + or -, not a >
To make it smoother you can adjust the DimmerStep

Now if you want to change that mode, the code is there 
https://github.com/arendst/Tasmota/blob/development/tasmota/tasmota_support/support_switch_v4.ino

If you want to change it for you, feel free but Tasmota will not change that

**Comment by pimw1** [comment]
Thank you for your reply. Let me try to explain better. Or perhaps i am misunderstanding you?

- all of the above was about switchmode11: switch1#state=2, switch1#state=4, switch1#state=7, are alle executed in this  switchmode11
- my goal is to get smooth dimming. The smoothest dimming is achieved by starting a dimming procedure (dimmer >) once, and than interrupting it (dimmer !) when it's dimmed to the required level. This concept is very nicely explained here <https://github.com/arendst/Tasmota/pull/11269>

Therefore, i am looking for a method to trigger the "dimmer >" exactly once (instead of repeatingly), when holding down a physical button.  A "Dimmer +" combined with a DimmerStep would deviate from the smoothest strategy available.

edit: i've tested the "Dimmer +"  with  Dimmerstep procedure yesterday via the switch1#state=4 trigger. I see where you are coming from. It achieves a somewhat smooth dimming experience, but it is not perfect. By  fiddling with the speed and dimmerstep you can make it better (been there, done that), but it's never gonna be perfect.

Dimming is perfect when i send the "dimmer >" once, followed by "dimmer !". It's amazing to see and gives a luxurious effect.

**Reply by barbudor** [reply]
I think that everything clear

You have perfectly understood how switchmode 11 is supposed to be used as described in the doc
You have explain that you would like it to behave differently in order to use it differently

So I explain that you need to change the code and I have pointed you where is the code to change.

**Reply by pimw1** [reply]
Aah ok, i understand you know. Thanks. Since i am new to Tasmota, i'm afraid this will not be an easy task for me. Perhaps someone knows how to tackle this one?

**Reply by barbudor** [reply]
What about setting SetOption 32 to a very long time?
If longer than the time needed to go through the whole dimming range, you would have only 1 state=4
Not sure but worth a try

**Reply by pimw1** [reply]
Yeah, i was thinking about that, but the drawback is that the initial longpress will also be delayed. Therefore, i am considering something else:

- keep setoptions32 short
- when switch1#state=4 is triggered, the setoptions32 is changed to a large value, followed by the "dimmer >" command
- when switch1#state=7 is triggered, the setoptions32 is changed to the short value again, followed by the "dimmer !" command

That might work.

**Reply by pimw1** [reply]
This strategy is not working.

```
Rule1
on switch1#state=2 do Backlog Speed 1; event power_signal=1 ENDON
on switch1#state=4 do Backlog SetOption32 63; DIMMER > ENDON
on switch1#state=7 do Backlog DIMMER !; SetOption32 6 ENDON
on switch2#state=2 do Backlog Speed 1; event power_signal=1 ENDON
on switch2#state=4 do Backlog SetOption32 63; DIMMER < ENDON
on switch2#state=7 do Backlog DIMMER !; SetOption32 6 ENDON
on event#power_signal=1 do Backlog POWER TOGGLE; Speed 10 ENDON
```

It keeps producing the state=4 events in a high frequency.  The frequency is drasticly reduced (from every 0.2 seconds to every 2.5 seconds), so it is somewhat better.

> 16:57:09.908 RUL: SWITCH2#STATE=4 performs "Backlog SetOption32 63; DIMMER <"
> 16:57:09.923 MQT: stat/hobbykamer_uplighter/RESULT = {"SetOption32":63}
> 16:57:10.108 RUL: SWITCH2#STATE=4 performs "Backlog SetOption32 63; DIMMER <"
> 16:57:10.124 MQT: stat/hobbykamer_uplighter/RESULT = {"POWER":"ON","Dimmer":1}
> 16:57:10.331 MQT: stat/hobbykamer_uplighter/RESULT = {"SetOption32":63}
> 16:57:10.542 MQT: stat/hobbykamer_uplighter/RESULT = {"POWER":"ON","Dimmer":1}
> 16:57:12.661 RUL: SWITCH2#STATE=4 performs "Backlog SetOption32 63; DIMMER <"
> 16:57:12.675 MQT: stat/hobbykamer_uplighter/RESULT = {"SetOption32":63}
> 16:57:12.879 MQT: stat/hobbykamer_uplighter/RESULT = {"POWER":"ON","Dimmer":1}
> 16:57:15.162 RUL: SWITCH2#STATE=4 performs "Backlog SetOption32 63; DIMMER <"
> 16:57:15.176 MQT: stat/hobbykamer_uplighter/RESULT = {"SetOption32":63}
> 16:57:15.386 MQT: stat/hobbykamer_uplighter/RESULT = {"POWER":"ON","Dimmer":1}
> 16:57:15.816 RUL: SWITCH2#STATE=7 performs "Backlog DIMMER !; SetOption32 6"
> 16:57:15.830 MQT: stat/hobbykamer_uplighter/RESULT = {"Dimmer":1}
> 16:57:16.027 MQT: stat/hobbykamer_uplighter/RESULT = {"SetOption32":6}

Funny enough, a simpler solution with a fixed value "SetOption32 63" works out exactly the same:

```
Rule1
on switch1#state=2 do Backlog Speed 1; event power_signal=1 ENDON
on switch1#state=4 do DIMMER > ENDON
on switch1#state=7 do DIMMER ! ENDON
on switch2#state=2 do Backlog Speed 1; event power_signal=1 ENDON
on switch2#state=4 do DIMMER < ENDON
on switch2#state=7 do DIMMER ! ENDON
on event#power_signal=1 do Backlog POWER TOGGLE; Speed 10 ENDON
```

> 17:01:00.775 RUL: SWITCH2#STATE=4 performs "DIMMER <"
> 17:01:00.783 MQT: stat/hobbykamer_uplighter/RESULT = {"POWER":"ON","Dimmer":1}
> 17:01:03.323 RUL: SWITCH2#STATE=4 performs "DIMMER <"
> 17:01:03.331 MQT: stat/hobbykamer_uplighter/RESULT = {"POWER":"ON","Dimmer":1}
> 17:01:05.606 RUL: SWITCH2#STATE=7 performs "DIMMER !"
> 17:01:05.614 MQT: stat/hobbykamer_uplighter/RESULT = {"POWER":"ON","Dimmer":3}

Two observations:
1: The initial time to recognize long-press is not influenced by setoptions 63 (which is good for my use case). This is not in line with the documentation:

> When pressing the button (closing the circuit) for a long time (set in SetOption32), Tasmota will send repeated INC_DEC (increment or decrement the dimmer) commands for as long as the button is pressed (use Switch<x>#state=4 in rules).

2: the increments of SetOption32 are not 0.1 seconds, but more like 0.04 seconds (see the log times. Delta of 2.5 seconds / 63 = 0.04). The documentation is not very explicit about the relationship between the frequency of the repeated INC_DEC and the value given for SetOption32.

Your thoughts are welcome. Any strategy for my use case would be very helpful.

**Reply by pimw1** [reply]
The ideal solution would be to introduce a variable to set the frequency of the repeated INC_DEC. That is the missing part here.

**Comment by pimw1** [comment]
Apart from this, i do think that there is strong case to implement this variaton for swithmode11: the "dimmer >" + "dimmer!" strategy is not properly supported for buttons. Which is kinda strange, since it's the defacto standard of Philips Hue and other zigbee brands.

**Comment by pimw1** [comment]
I've went with a different strategy, since i was unable to find an easy solution to filter down on the high-frequent switch1#state=4 triggers. I'm now sending MQTT messages for dimming, which are used as triggers in a Home Assistant automation. Within that Home Assistant automation, i'm using an input boolean so that dimming signal is only send once.

This works fine and gives the smoothest dimming effect. But it also shows that there is a functional gap in the Tasmota feature set (the smoothest dimming methodology is not supported).

Tasmota:
```
Rule1
on switch1#state=2 do Backlog Speed 1; event power_signal=1 ENDON
on switch1#state=4 do Publish stat/hobbykamer_uplighter/switch Dimmer > endon
on switch1#state=7 do Publish stat/hobbykamer_uplighter/switch Dimmer ! endon
on switch2#state=2 do Backlog Speed 1; event power_signal=1 ENDON
on switch2#state=4 do Publish stat/hobbykamer_uplighter/switch Dimmer < endon
on switch2#state=7 do Publish stat/hobbykamer_uplighter/switch Dimmer ! endon
on event#power_signal=1 do Backlog POWER TOGGLE; Speed 10 ENDON
```

Home Assistant:
```
alias: uplighter automation
description: ""
trigger:
  - platform: mqtt
    topic: stat/uplighter/switch
    id: dim_down
    payload: Dimmer <
  - platform: mqtt
    topic: stat/uplighter/switch
    id: dim_stop
    payload: Dimmer !
  - platform: mqtt
    topic: stat/uplighter/switch
    id: dim_up
    payload: Dimmer >
  - platform: mqtt
    topic: stat/uplighter/switch
    id: dim_stop
    payload: Dimmer !
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: dim_down
          - condition: state
            entity_id: input_boolean.hobbykamer_dimstatus
            state: "off"
        sequence:
          - parallel:
              - service: input_boolean.turn_on
                data: {}
                target:
                  entity_id: input_boolean.hobbykamer_dimstatus
          - service: mqtt.publish
            data:
              topic: cmnd/uplighter/Dimmer
              qos: 0
              retain: false
              payload: <
      - conditions:
          - condition: trigger
            id: dim_stop
        sequence:
          - parallel:
              - service: mqtt.publish
                data:
                  topic: cmnd/uplighter/Dimmer
                  qos: 0
                  retain: false
                  payload: "!"
              - service: input_boolean.turn_off
                data: {}
                target:
                  entity_id: input_boolean.hobbykamer_dimstatus
      - conditions:
          - condition: trigger
            id: dim_up
          - condition: state
            entity_id: input_boolean.hobbykamer_dimstatus
            state: "off"
        sequence:
          - parallel:
              - service: mqtt.publish
                data:
                  topic: cmnd/uplighter/Dimmer
                  qos: 0
                  retain: false
                  payload: ">"
              - service: input_boolean.turn_on
                data: {}
                target:
                  entity_id: input_boolean.hobbykamer_dimstatus
      - conditions:
          - condition: trigger
            id: dim_stop
        sequence:
          - parallel:
              - service: mqtt.publish
                data:
                  topic: cmnd/uplighter/Dimmer
                  qos: 0
                  retain: false
                  payload: "!"
              - service: input_boolean.turn_off
                data: {}
                target:
                  entity_id: input_boolean.hobbykamer_dimstatus
    default: []
mode: parallel
```
