### DISCUSSION TITLE
Maximizing the console height

### DISCUSSION THREAD

**Discussion by wolph** [arendst/Tasmota#19241] [Ideas]
The tasmota console height is currently fixed to 318 pixels which just wastes a lot of space that could be used. With a tiny bit of css I've increased it to scale to the screen height, but I'm not sure if this works in all cases with all monitors. Perhaps there's some weirdness that I didn't think of :)

In any case, this works for me for both the berry and the regular console:
```css
textarea#t1{
    height: calc(100vh - 340px);
}
div#t1{
    height: calc(100vh - 430px);
}
```

I've added it as a userstyle right now using the following regex url rule: `http://\d+\.\d+\.\d+\.\d+/(cs\?|bc)`

Test the userstyle from here: https://userstyles.world/style/11283/tasmota-console-height
