### DISCUSSION TITLE
Tasmota Plug turn off when Router is restarted

### DISCUSSION THREAD

**Discussion by BlueWings172** [arendst/Tasmota#19851] [Q&A] [answered]
Hello

I'm using several Tasmota devices with last version 13.2 and MQTT Broker (mosquitto) 

I'm facing an issue with 2 devices (Sonoff S26 smart plug and Sinilink XY-WPCE.

When they loose wi-fi connectivity (router restart for example), they turn the relays off.

I think this is related to retained messages and I can see them in the broker (MQTT Explorer) and I delete the messages but next time when router is restarted same thing happens.

How do I get rid of this behavior once of for all ?

Thanks!

![image](https://github.com/arendst/Tasmota/assets/65966061/db0cfcea-7228-4073-84af-5ec4490c3e47)

**Comment by BlueWings172** [comment]
Hello,
Does anyone have a solution. This is an ongoing problem for months without solution. I have tried everything I found online.

This happens at least twice a day. It turns off my PC in the middle of work and it turns off my 3d printer in the middle of prints. I've lost lots of work and prints because of it.

I would really appreciate any help!

**Reply by sfromis** [reply]
Well, if it is retained messages coming again, you need to stop publishing retained commands from wherever you are doing that, and of course delete what you have. In general, **never** use retained commands, unless you know exactly why you *want* that, and that you are ok with the common pitfalls of retained commands, like what you are seeing. 

If you "insist" on using retained messages, each and every change to the *desired* status has to be reflected in having such retained commands, but again, I'd recommend not using retained commands, unless you *really* know what you are doing and signing up for.

**Reply by BlueWings172** [reply]
@sfromis,

Thanks for the reply. I have no need and no intention to use retained messages. I don't know from where and why they appear.

I use MQTT Explorer to delete them after they cause my PC and Plug to power off but they appear again and I don't know why.

Is there a way to find out why this is happening ?

**Reply by barbudor** [reply]
You may find clues in the mosquitto logs

**Reply by sfromis** [reply]
Retained messages **only** are created if this flag is actively being set when doing a publish. Look for where those publish are being done.

**Reply by BlueWings172** [reply]
@sfromis  @barbudor Thank you both for your help! I appreciate it. However, I'm still having trouble figuring out what to do as I am not an advanced user. I have Home Assistant set up with Tasmota devices and an MQTT broker. I'm not sure if Home Assistant is publishing retained messages, and I'm unsure how to check this and correct it if necessary. My Tasmota devices are configured to connect to the broker on startup. Any guidance on how to troubleshoot this would be greatly appreciated.

below some info:

- Devices with issue: Sinilink XY-WPCE (<<most frequent issue) and Sonoff S26
- Both running Tasmota 14.0 (issue been preseent for many versions)
- I have total 11 Tasmota devices with no issues except those 2
- In both devices, I have noticed that the Tasmota configuration pages shows the bleow:
- MQTT No Retain	Disabled	(but all my other devices show the same.)
- I have not made any configuration to my Mosquitto MQTT Broker. I just installed it and it runs.
- For Sinilink I have a switch configured in HA with below code in configuration.yaml

```
switch:
  - platform: template
    switches:
      cyberswitch:
        unique_id: "CyberPower_Switch"
        value_template: "{{ is_state('binary_sensor.switch1', 'on') }}"
        availability_template: "{{ not is_state('binary_sensor.switch1', 'unavailable') }}"
        turn_on:
          service: switch.toggle
          target:
            entity_id: switch.Tasmota_PC
        turn_off:
          service: switch.toggle
          target:
            entity_id: switch.Tasmota_PC
        icon_template: >-
          {% if is_state('binary_sensor.switch1', 'on') %}
            mdi:power-plug
          {% else %}
            mdi:power-plug-off
          {% endif %}            


```
for S26 I have a simple automation to toggle the S26 with an RF remote.


Thanks for your help
