### DISCUSSION TITLE
SmartMeter Interface for Apator Apox+

### DISCUSSION THREAD

**Discussion by nevyen** [arendst/Tasmota#20824] [Q&A]
I've got a new Power-Measurement-Unit (Apator Apox+).

I found in also in the documentation #https://tasmota.github.io/docs/Smart-Meter-Interface/#apator-apox-sml

After unlocking the info output with a pin I put the skript in my tasmota web interface. But I got no data. 

Having a look with my mobile-camera the right diode on the smart meter flashes. 
Setting the tasmota to debug mode with `Sensor53 d1` results in the following output: 
```
11:32:13.909 CMD: Sensor53 d1
11:32:13.916 MQT: stat/CTS_tasmota_SML_0FE099/RESULT = {"Time":"2024-02-28T11:32:13","SML":{"CMD":"dump: 1"}}
```
But it seems there is no data incoming from the diode. 

I'm new to this so I have no idea what the problem could be. 

Following test were made:
- rotate Tasmotasensor by 180 degree
- test another smart meter -> hex output on console

Any hints are welcome :-) 

Thanks in advance

**Comment by MkeFobe** [comment]
I'm using esphome but have the same meter so I came across here.
It works fine for me, but you have to enable the Info interface, then it sends every second the current power consumption and the total. 
Also I have disabled the PIN protection.
Link to the manual in german: https://www.manualslib.de/manual/631636/Apator-Apoxplus.html?page=4#manual

**Reply by nevyen** [reply]
I also enabled the Info interface and disabled the pin. 

But somehow there is no data on my Sensor.

**Comment by MkeFobe** [comment]
That's the snippet I used in the ESPHome yaml:
```
uart:
  id: uart_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600

sml:
  id: mysml
  uart_id: uart_bus

sensor:
  - platform: sml
    name: "Total energy"
    sml_id: mysml
    obis_code: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 0
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.000001
      - throttle: 60s
  - platform: sml
    name: "Total energy OUT"
    sml_id: mysml
    obis_code: "1-0:2.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 0
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.000001
      - throttle: 60s
  - platform: sml
    name: "Current Power"
    sml_id: mysml
    obis_code: "1-0:16.7.0"
    unit_of_measurement: W
    accuracy_decimals: 0
    filters:
      - multiply: 0.001
    device_class: power
    state_class: measurement
```
