### DISCUSSION TITLE
tasmota hvac unit hass autodiscovery via berry

### DISCUSSION THREAD

**Discussion by ouinouin** [arendst/Tasmota#20897] [General]
hi, 
i m actually in the process of writing a HVAC control : berryton  , to control airton units through their serial port via tasmota.
for now i need to declare manually the unit in homeassistant as HVAC unit. like this : 

```
    - name: NewAirton
      unique_id: climate.NewAirton
      max_temp: 31.0
      min_temp: 16.0
      modes:
        - "auto"
        - "off"
        - "cool"
        - "heat"
        - "dry"
        - "fan_only"
      swing_modes:
        - "on"
        - "off"
        - "low"
        - "medium-low"
        - "medium"
        - "medium-high"
        - "high"
      fan_modes:
        - "turbo"
        - "high"
        - "medium-high"
        - "medium"
        - "low-medium"
        - "low"
        - "quiet"
        - "auto"
      #initial: 21
      current_temperature_topic : "nodered/temp-salon"
      power_command_topic: "cmnd/Newclim/power/set"
      mode_command_topic: "cmnd/Newclim/mode/set"
      temperature_command_topic: "cmnd/Newclim/temperature/set"
      fan_mode_command_topic: "cmnd/Newclim/fan/set"
      swing_mode_command_topic: "cmnd/Newclim/swing/set"
      
      fan_mode_state_topic: "tele/Newclim/fan/get"
      swing_mode_state_topic: "tele/Newclim/swing/get"
      mode_state_topic: "tele/Newclim/mode/get"
      temperature_state_topic: "tele/Newclim/Actualsetpoint/get"
      precision: 0.1

```
I would like to benefit from the autodiscovery , i see in tasmotat source that thing happen here :
[tasmota home assistant driver ](https://github.com/arendst/Tasmota/blob/6d82997fde0f79c4d846de0ab4d96420f980af58/tasmota/tasmota_xdrv_driver/xdrv_12_home_assistant.ino#L1060)
i d like to know if i can implement the autodiscovery mecanism in berry alone , sinc as not being a great C coder, i foresee having more chances to  succeeed in berry.
what i still dont understand is what shall i send for the tasmota plugin of home assistant understands i m sending an autodiscovery for a HVAC unit, has the plugin to be updated to support that or is the tasmota homeassistant plugin already featured to accept all classes of material already supported by homeassistant in mqtt ?
