### DISCUSSION TITLE
Tasmota on TUYAMCU and mqtt climate thermostat

### DISCUSSION THREAD

**Discussion by renellis** [arendst/Tasmota#22747] [Show and tell]
I'm currently working on this project:

https://community.home-assistant.io/t/berg-glass-panel-heater-tuya-to-tasmota/818597

I still have issues with the thermostat, essentially it doesn't seems to get when the heater is on:

![image](https://github.com/user-attachments/assets/b5bd815e-e102-45a4-aae9-de36ab343264)

This the current settings in home assistant:

```
mqtt:
  - climate:
      name: "Panel Heater Office"
      unique_id: "esp_panel_heater_office_climate"
      modes:
       - "off"
       - "heat"
      mode_command_topic: "cmnd/panel_heater_office/POWER1"
      mode_command_template: "{{'1' if value == 'heat' else '0'}}"
      mode_state_topic: "tele/panel_heater_office/STATE"
      mode_state_template: "{{'POWER1' if value == 'ON' else 'off'}}"
      current_temperature_topic: "tele/panel_heater_office/SENSOR"
      current_temperature_template: "{{value_json['TuyaSNS']['Temperature']}}"
      temperature_state_topic: "tele/panel_heater_office/SENSOR"
      temperature_state_template: "{{value_json['TuyaSNS']['TempSet']}}"
      min_temp: 16
      max_temp: 25
      precision: 0.5
      temperature_command_topic: "cmnd/panel_heater_office/TUYASEND2" 
      temperature_command_template: "3,{{value|int}}"

```
